### ISSUE TITLE
Rename Gnatcatcher

### ISSUE THREAD

**Issue by miketaylr** [GoogleChromeLabs/privacy-sandbox-explainer-updates#11]
Hey @bjsmith16, should we rename "Gnatcatcher" to "IP Protection" now? WDYT?

**Comment by bjsmith16** [comment]
That makes sense to me. Give me a couple of days just to confirm it with other teams and I will let you know!

**Comment by bjsmith16** [comment]
Checked in with the relevant teams and no issues. Lets do this on 4/3 to give them time to update presentation materials.

**Comment by miketaylr** [comment]
OK - today is 4/3, so let's do it.
